apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion
spec:
  replicas: 3 # El número de réplicas que deseas ejecutar
  selector:
    matchLabels:
      app: mi-aplicacion
  template:
    metadata:
      labels:
        app: mi-aplicacion
    spec:
      containers:
      - name: app-muebles
        image: alanfvn/parcialdos:v1
        ports:
        - containerPort: 8585 # El puerto en el que se ejecuta tu aplicación
